### PR TITLE
Add Code Owners.

### PR DESCRIPTION
**Pull request by ZakFong**
# Description

Add code owners which was previously  missed.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by ZakFong** [comment]
ok


Vanessa Cooper ***@***.***>於 2022年11月19日 週六，07:47寫道：

**Review by vanessa-cooper — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Comment by ZakFong** [comment]
Done.

Vanessa Cooper ***@***.***>於 2022年11月19日 週六，08:01寫道：

**Pull request merged**
